accounts/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path, include
from accounts.forms import UserLoginForm
from accounts.views import RegisterView, edit_profile

urlpatterns = [
    path('login/', LoginView.as_view(authentication_form=UserLoginForm),name='login'),
    path('register/', RegisterView.as_view(),name='register'),
    path('profile/', edit_profile,name='profile'),
    path('', include('django.contrib.auth.urls'))
]

projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ProjectListView.as_view(),name='project_list'),
    path('project/create/', views.ProjectCreateView.as_view(),name='project_create'),
    path('project/<int:pk>/update/', views.ProjectUpdateView.as_view(),name='project_update'),
    path('project/<int:pk>/delete', views.ProjectDeleteView.as_view(),name='project_delete'),
    path('task/create/', views.TaskCreateView.as_view(),name='task_create'),
    path('task/<int:pk>/delete/', views.TaskDeleteView.as_view(),name='task_delete'),
    path('task/<int:pk>/update/', views.TaskUpdateView.as_view(),name='task_update')
]

projects_management/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.utils.translation import gettext as _

admin.site.site_header =_("Projects Management")
admin.site.site_title =_("Projects Management")

urlpatterns = [
    path('', include('projects.urls')),
    path('accounts/', include('accounts.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('admin/', admin.site.urls),
]

projects/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext as _

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Category")

class ProjectStatus(models.IntegerChoices):
    PENDING = 1, _('Pending')
    COMPLETED = 2, _('Completed')
    POSTPONED = 3, _('Postponed')
    CANCELED = 4, _('Canceled')

class Project(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    status = models.IntegerField(choices=ProjectStatus.choices, default=ProjectStatus.PENDING)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,null=True)
    #PROTECT:idha fasa5t category mattfasa5ch lmachari3 eli 3andha 3ale9a bil category hadhika
    #CASCADE:idha fasa5t l user yetfasa5 lmachari3 mte3o lkol
    class Meta:
        verbose_name = _("Project")
        verbose_name_plural = _("Project")

    def __str__(self):
        return self.title

class Task(models.Model):
    description = models.TextField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    class Meta:
        ordering = ["is_completed"]
        verbose_name = _("Task")
        verbose_name_plural = _("Task")
    def __str__(self):
        return self.description

projects/forms.py
from django import forms
from . import models
from django.utils.translation import gettext as _
attrs = {'class': 'form-control'}
class ProjectCreateForm(forms.ModelForm):
    class Meta:
        model = models.Project
        fields = ['category', 'title', 'description']
        labels = {
            'category':_('Category'),
            'title':_('Title'),
            'description':_('Description')
        }
        widgets = {
            'category': forms.Select(attrs=attrs),
            'title': forms.TextInput(attrs=attrs),
            'description': forms.Textarea(attrs=attrs)
        }

class ProjectUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Project
        fields = ['category', 'title', 'status']
        widgets = {
            'category': forms.Select(attrs=attrs),
            'title': forms.TextInput(attrs=attrs),
            'status': forms.Select(attrs=attrs)
        }

projects/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from . import models
from . import forms
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
# Create your views here.
class ProjectListView(LoginRequiredMixin, ListView):
    model = models.Project
    template_name = 'project/project_list.html'
    paginate_by = 6
    def get_queryset(self):
        query_set = super().get_queryset()
        where = {'user_id':self.request.user}
        query = self.request.GET.get('query',None)
        if query:
            where['title__icontains'] = query
        return query_set.filter(**where)

class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = models.Project
    form_class = forms.ProjectCreateForm
    template_name = 'project/project_create.html'
    success_url = reverse_lazy('project_list')
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form )

class ProjectUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = models.Project
    form_class = forms.ProjectUpdateForm
    template_name = 'project/project_update.html'
    def test_func(self):
        return self.get_object().user_id == self.request.user.id
    def get_success_url(self):
        return reverse('project_update', args=[self.object.id])

class ProjectDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = models.Project
    template_name = 'project/project_delete.html'
    success_url = reverse_lazy('project_list')
    def test_func(self):
        return self.get_object().user_id == self.request.user.id

class TaskCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = models.Task
    fields = ['project','description']
    http_method_names = ['post']
    def test_func(self):
        project_id = self.request.POST.get('project','')
        return models.Project.objects.get(pk=project_id).user_id == self.request.user.id
    def get_success_url(self):
        return reverse('project_update', args=[self.object.project.id])
    #self.object.project.id t5alina n3od lsaf7et idarat al machro3

class TaskUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = models.Task
    fields = ['is_completed']
    http_method_names = ['post']

    def test_func(self):
        return self.get_object().project.user_id == self.request.user.id

    def get_success_url(self):
        return reverse('project_update', args=[self.object.project.id])

class TaskDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = models.Task
    def test_func(self):
        return self.get_object().project.user_id == self.request.user.id
    def get_success_url(self):
        return reverse('project_update', args=[self.object.project.id])

projects/templates/project/project_create.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="card col-md-6 px-6">
                <div class="card-header">
                    <h3 class="mb-0 py-2">{% trans 'New Project' %}</h3>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% include 'common/form.html' with form=form %}
                        <button class="btn btn-success">
                            {% translate 'Create' %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

projects/templates/project/project_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

    <h2>{% trans 'Alert' %}</h2>
    <form method="post">
        {% csrf_token %}
        <p class="text-muted my-4">
            {% trans 'are you sure to delete' %} {{project.title}}?
            <!-- fi 9aweleb django nasta3mel project 3iwadhan 3an Project alati hya to3ado kitaba
            5asa bil classet fi python ama fi django naktob project-->
        </p>
        <input class="btn btn-danger" type="submit" value="{% trans 'Delete'%}">
    </form>
{% endblock %}

projects/templates/project/project_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load humanize %}

{% block content %}
    <div class="d-flex">
        <h3 class="me-auto">{% trans 'My Projects' %}</h3>
        <div>
            <a href="{% url 'project_create' %}" class="btn btn-outline-success">
                <i class="bi bi-plus-lg"></i> {% trans 'New Project' %}
            </a>
        </div>
    </div>

    <div class="row my-5">
        {% for project in object_list %}
            <div class="col-md-4">
                <div class="card mb-3">
                    <div class="card-body">
                        <p>
                            <span class="badge rounded-pill bg-dark">
                                {{project.get_status_display}}
                            </span>
                        </p>
                        <h3 class="card-title fs-6">{{project.title}}</h3>
                        <p class="card-text text-muted small">{{project.description}}</p>
                        <div class="d-flex">
                            <span class="me-auto text-muted small">
                                <i class="bi bi-clock"></i>
                                <time datetime="{{project.created_at}}">{{project.created_at|naturaltime}}</time>
                            </span>
                            <a href="{% url 'project_update' project.id %}" class="btn btn-sm btn-outline-success mx-1">
                                {% trans 'Edit' %}
                            </a>
                            <a href="{% url 'project_delete' project.id %}" class="btn btn-sm btn-outline-danger">
                                <i class="bi bi-trash"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col-md-12">
                <div class="h-100 p-5 bg-white border rounded-3 text-center">
                    <p>{% trans 'there are no projects to show' %}</p>
                    <p>
                        <i class="bi bi-emoji-frown fs-1"></i>
                    </p>
                    <a href="{% url 'project_create' %}" class="btn btn-success">
                        <i class="bi bi-plus-lg"></i> {% trans 'New Project' %}
                    </a>
                </div>
            </div>
        {% endfor %}
        {% if page_obj.paginator.count > 0 %}
            <div class="d-flex justify-content-center bd-highlight mb-3">
                <nav>
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.previous_page_number}}">
                                    {% trans 'Previous' %}
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#">{% trans 'Previous' %}</a>
                            </li>
                        {% endif %}

                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.next_page_number}}">
                                    {% trans 'Next' %}
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#">{% trans 'Next' %}</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        {% endif %}
    </div>

{% endblock %}

projects/templates/project/project_update.html
{% extends 'base.html' %}
{% load i18n %}
{% load humanize %}

{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <h3>
                    {{object.title}}
                </h3>
            </li>
        </ol>
    </nav>

    <div class="row">

        <div class="col-md-3">
            <form method="post">
                <div class="card">

                    <div class="card-body">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="mb-3">{{field}}</div>
                        {% endfor %}

                        <div class="d-flex mt-2">
                            <span class="me-auto text-muted small">
                                <i class="bi bi-clock"></i>
                                <time datetime="{{object.created_at}}">
                                    {{object.created_at|naturaltime}}
                                </time>
                            </span>
                        </div>

                    </div>
                    <div class="card-footer">
                        <div class="d-grid gap-2">
                            <button class="btn btn-success">
                                <i class="bi bi-save"></i>
                                {% trans 'Save' %}
                            </button>
                            <button class="btn btn-danger">
                                <i class="bi bi-trash"></i>
                                {% trans 'Delete' %}
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div class="col-md-9">
            {% include 'project/task.html' with project=object %}
        </div>

    </div>

{% endblock %}

projects/templates/project/task.html
{% load i18n %}

<ul class="list-group">
    {% for task in project.task_set.all %}
        <li class="list-group-item d-flex">
            <form method="post" action="{% url 'task_update' task.id %}" class="my-auto me-2">
                {% csrf_token %}
                <input
                    class="form-check-input"
                    type="checkbox"
                    name="is_completed"
                    {% if task.is_completed %} checked {% endif %}
                    onchange="this.form.submit()"
                >
            </form>
            <p class="my-auto me-auto">
                {{task.description}}
            </p>
            <form method="post" action="{% url 'task_delete' task.id %}">
                {% csrf_token %}
                <button type="submit" class="btn"><i class="bi bi-trash text-danger"></i></button>
            </form>
        </li>
    {% endfor %}
</ul>

<div class="card mt-2">
    <form method="post" action="{% url 'task_create' %}">
        {% csrf_token %}
        <div class="input-group">
            <input type="hidden" value="{{project.id}}" name="project">
            <input type="text" class="form-control" placeholder="{% trans 'New Task' %}" name="description" required>
            <input type="submit" class="btn btn-outline-dark" value="{% trans 'Add' %}">
        </div>
    </form>
</div>